site_name: TechNotes
site_url: https://yyyyl.github.io/TechNotes/

theme:
  name: yeti
  nav_style: light

pages:
  - 主页: "index.md"
  - 目录:
    - C/C++:
      - C++11 智能指针: "C_CPP/SmartPointer/SmartPointer.md"
      - C程序内存空间划分: "C_CPP/Memory/MemoryLayoutOfProgram.md"
    - 渲染:
      - Gamma矫正: "Rendering/Gamma/GammaCorrection.md"
      - PBR: "Rendering/PBR/PBR.md"

markdown_extensions:
  - mdx_math
  
extra_javascript:
- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'