site_name: TechNotes

theme:
  name: yeti
  nav_style: light

pages:
  - 主页: "index.md"
  - 目录:
    - C/C++:
      - C++11 智能指针: "C_CPP/SmartPointer/SmartPointer.md"
      - C程序内存空间划分: "C_CPP/Memory/MemoryLayoutOfProgram.md"